app:
  cookie:
    session:
      name: {{ app.cookie.session.name }}
      expiration: {{ app.cookie.session.expiration }}
  service:
    user:
      session_secret: {{ app.service.user.session_secret }}
  http:
    port: {{ app.http.port }}
  cors:
    allow_origins: {{ app.cors.allow_origins }}
    allow_credentials: {{ app.cors.allow_credentials }}
    max_age: {{ app.cors.max_age }}
  logger:
    loglvl: info
    mode: production
    encoding: json
  scheduler:
    refresh_search_table_pattern: {{ app.scheduler.refresh_search_table_pattern }}
  vk:
    http:
      timeout: {{ app.vk.http.timeout }}
    auth:
      url: {{ app.vk.auth.url }}
      client_id: {{ app.vk.auth.client_id }}
    secret: {{ app.vk.secret }}

postgres:
  host: {{ app.postgres.host }}
  port: {{ app.postgres.port }}
  user: {{ app.postgres.user }}
  password: {{ app.postgres.password }}
  dbname: {{ app.postgres.dbname }}
  sslmode: {{ app.postgres.sslmode }}

redis:
  addr: {{ app.redis.addr }}
  password: {{ app.redis.password }}
  db: {{ app.redis.db }}
