---
- name: setup/update ssl certs
  hosts: all
  become: true

  vars:
    domain_list:
      - vixar.tech
      - www.vixar.tech
    email: "dan.mironenko@gmail.com"
    webroot_path: /opt/apps/front-nginx/data/certbot
    nginx_dir: /opt/apps/front-nginx/deploy
    nginx_service: front-nginx

  tasks:
    - name: check webroot path exists
      ansible.builtin.file:
        path: "{{ webroot_path }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: install certbot and dependencies
      ansible.builtin.apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: latest
        update_cache: yes

    - name: obtain or renew certs
      ansible.builtin.command: >
        certbot certonly
        --webroot -w {{ webroot_path }}
        {% for d in domain_list %} -d {{ d }}{% endfor %}
        --non-interactive --agree-tos --email {{ email }}

    - name: restart nginx
      ansible.builtin.command:
        chdir: "{{ nginx_dir }}"
        cmd: docker restart {{ nginx_service }}

    - name: setup certbot auto-renew
      ansible.builtin.cron:
        name: "certbot auto-renew"
        user: ubuntu
        minute: "0"
        hour: "3"
        job: >
          certbot renew --quiet --post-hook
          "docker restart {{ nginx_service }}"
        state: present
